services:
  - type: web
    name: west-alabama-occ
    env: docker
    dockerfilePath: ./Dockerfile
    dockerBuildContext: .
    envVars:
      - key: REACT_APP_SUPABASE_URL
        sync: false
      - key: REACT_APP_SUPABASE_ANON_KEY
        sync: false