services:
  - type: web
    name: west-alabama-occ
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: docker build --build-arg REACT_APP_SUPABASE_URL=${REACT_APP_SUPABASE_URL} --build-arg REACT_APP_SUPABASE_ANON_KEY=${REACT_APP_SUPABASE_ANON_KEY} -t west-alabama-occ .
    envVars:
      - key: REACT_APP_SUPABASE_URL
        sync: false
      - key: REACT_APP_SUPABASE_ANON_KEY
        sync: false